# Generated by Django 4.2.10 on 2024-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='予約ID'),
        ),
    ]
