# Generated by Django 4.2.10 on 2024-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_alter_category_id_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='お気に入りID'),
        ),
    ]
