# Generated by Django 4.2.10 on 2024-04-05 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tabelog', '0003_diaryuser_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('first_name', models.CharField(max_length=30, verbose_name='姓')),
                ('last_name', models.CharField(max_length=30, verbose_name='名')),
                ('telephone_number', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('post_code', models.CharField(blank=True, max_length=30, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='住所')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入会日')),
                ('is_active', models.BooleanField(default=True, verbose_name='staff status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DiaryUser',
        ),
    ]
