# Generated by Django 4.2.10 on 2024-06-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_alter_like_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='like_unique',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('store', 'user')},
        ),
    ]
