# Generated by Django 4.2.10 on 2024-04-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_customuser_delete_diaryuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
