# Generated by Django 4.2.10 on 2024-04-05 06:41

from django.db import migrations
import tabelog.models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', tabelog.models.CustomUserManager()),
            ],
        ),
    ]
