# Generated by Django 4.2.10 on 2024-04-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0007_alter_customuser_options_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
